# Generated by Django 4.2.4 on 2023-12-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_learning_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='position',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='image_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(default='static/default-user.png', upload_to='team_photos/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
    ]
