# Generated by Django 4.2.4 on 2023-12-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_learning_app', '0002_rename_position_teammember_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(default='static/default-user.png', upload_to='static/team_photos/'),
        ),
    ]
