# Generated by Django 4.2.4 on 2023-12-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_learning_app', '0004_alter_teammember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(default='default-user.png', upload_to='team_photos/'),
        ),
    ]
